name:                coding-the-matrix
version:             0.1.0.0
github:              channikhabra/playing-around-with-haskell/coding-the-matrix
license:             BSD3
author:              Charanjit Singh
copyright:           2020 Charanjit Singh

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Some code I am writing while studying Coding the Matrix book

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src

executables:
  coding-the-matrix-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - coding-the-matrix
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  coding-the-matrix-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - coding-the-matrix
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
